[project]
name = "project"
version = "0.1.0"
requires-python = ">=3.10.0"
dependencies = [
    "numpy<2.0",
    "scikit-learn>=1.6.1",
    "sentence-transformers>=3.3.1",
    "torch<2.3.0",
    "pandas>=2.2.3",
    "jupyterlab>=4.3.5",
]
